name: homepage
description: nerg page
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.6
  rive: ^0.13.20
  webview_flutter: ^4.10.0
  # flame_rive: ^1.6.0
  # flame_forge2d: ^0.12.5
dev_dependencies:

flutter:
  assets:
    - nerg.riv
    - README.md
